### ISSUE TITLE
16.3 support

### ISSUE THREAD

**Issue by MagicAndre1981** [gekka/NewProjectTreeDialog#2]
Hi, can you please add support for 16.3 Update? When I create a new project the new shitty dialog is shown.

**Comment by gekka** [comment]
Updated to support Visual Studio 2019 16.3.5.

The dialog structure has changed due to minor changes in Visual Studio.
Probably It will be not work again after the next change.

**Comment by MagicAndre1981** [comment]
thanks. the author of the [extension that restores the buildin one](https://marketplace.visualstudio.com/items?itemName=softworkz.SwitchProjectDialog#overview) has updated this extension, too. MS changed some internal variables. So I'll use his one as long as possible und test yours if his is broken again.
